const Tram = require('tram-one')

const app = new Tram()
app.addRoute('/', require('./pages/home'))
app.addRoute('/404', require('./pages/404'))
app.addRoute('/drink/:drinkId', require('./pages/drink'))
app.addRoute('/filter', require('./pages/filter'))
app.addActions({drinkStore: require('./actions/drink-by-id')})
app.addActions({filterStore: require('./actions/filter-by-ingredients')})
app.start('.main')
